# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fa26159ee96e6d3380d56582bde336ae"
application_url = "https://bigfive-afiliadas.vercel.app"
embedded = true
name = "bigfive-afiliadas"

[access_scopes]
scopes = "read_orders,read_products,read_price_rules,read_discounts,write_price_rules,write_discounts"

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/paid"
  topics = [ "orders/paid" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/cancelled"
  topics = [ "orders/cancelled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/refunds/create"
  topics = [ "refunds/create" ]

[auth]
redirect_urls = [ "https://bigfive-afiliadas.vercel.app/auth/callback" ]

[build]
automatically_update_urls_on_dev = true
